name: bokehwkshp
channels:
  - bokeh
  - defaults
dependencies:
  - python =3.6
  - bokeh =0.12
  - notebook =5.0
  - pandas =0.19
  - jupyter
  - numpy
  - holoviews
  - datashader
  - anaconda-project
  - nodejs
